name: Deploy to GitHub Pages

on:
  push:
    branches:
      - site  # or your default branch name
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # or your build directory if you have one
          force_orphan: true  # Creates single-commit history on gh-pages branch
          cname: ${{ secrets.CNAME }}  # If you have a custom domain
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"